Repository conservation-laws/ryujin, pull requests merged in 2023-09, with the labels that each got.

#24 prm: add benchmark configurations
  prm/README.md
  prm/benchmarks/euler-mach10-double-mach-reflection.prm
  prm/benchmarks/euler-mach3-cylinder-2d.prm
  prm/benchmarks/euler-mach3-cylinder-3d.prm
  prm/benchmarks/euler-mach3-forward-facing-step.prm
  prm/benchmarks/navier_stokes-daru-tenaud-shocktube.prm
  prm/benchmarks/scalar_conservation-kpp.prm
  prm/todo/mach3-cylinder-2d.prm
  prm/todo/mach3-cylinder-3d.prm
  prm/todo/mach3-step.prm
  prm/todo/oat15a-2d.prm
  prm/todo/oat15a-3d.prm
  source/hyperbolic_module.template.h
  source/time_integrator.h
  source/time_integrator.template.h
  source/time_loop.h
  source/time_loop.template.h
Labels: documentation

#23 main: remove annoying warning
  source/main.cc
Labels: bug

#22 EulerAEOS: Update smooth wave initial state to work for arbitrary EOS
  source/euler/initial_state_smooth_wave.h
Labels: good-to-merge/minor-suggestions :+1:
