Repository conservation-laws/ryujin, pull requests merged in 2024-04, with the labels that each got.

#64 OffflineData: adjust to API changes for upcoming deal.II 9.6.0
  source/offline_data.template.h
Labels: good-to-merge/waiting-for-ci :+1:

#67 `NavierStokes`: Refactor parabolic solver
  prm/verification/navier_stokes-becker_solution-erk33.baseline
  source/navier_stokes/parabolic_solver.h
  source/navier_stokes/parabolic_solver.template.h
  source/parabolic_module.cc
  source/parabolic_module.h
  source/parabolic_module.template.h
  source/time_integrator.template.h
  tests/navier_stokes/gmg_energy.threads=1.output
  tests/navier_stokes/gmg_velocity.threads=1.output
  tests/navier_stokes/gmg_velocity_energy.threads=1.output
  tests/navier_stokes/verification-becker_solution-erk_33-l5-2d.threads=1.output
  tests/navier_stokes/verification-becker_solution-erk_33-l6.threads=1.output
  tests/navier_stokes/verification-becker_solution-ssprk_33-l5-2d.threads=1.output
Labels: good-to-merge/minor-suggestions :+1:

#72 Make things compile with my compiler.
  source/quantities.template.h
Labels: good-to-merge :+1:

#73 C++20 no longer captures 'this' implicitly in lambda functions.
  CMakeLists.txt
  source/euler/initial_state_becker_solution.h
Labels: good-to-merge :+1:

#74 OfflineData: fix sparsity pattern logic
  source/offline_data.template.h
Labels: bug
